# Generated by Django 4.1 on 2022-08-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kksproj', '0002_uploadimg_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
